
services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "6999:5432"
    environment:
      POSTGRES_USER: sae
      POSTGRES_PASSWORD: sae
      POSTGRES_DB: sae
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./tables.sql:/docker-entrypoint-initdb.d/tables.sql
    networks:
      default:

  tomcat:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
          - "6998:8080"

      depends_on:
          - postgres
      networks:
        default:
networks:
    default:
volumes:
  pg_data:










