
services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sae
      POSTGRES_PASSWORD: sae
      POSTGRES_DB: sae


    networks:
      default:

  tomcat:
      image: tomcat
      ports:
          - "8081:8080"
      volumes:
          - ./:/usr/local/tomcat/webapps/sae
          - ./lib/postgresql-42.7.5.jar:/usr/local/tomcat/lib/postgresql-42.7.5.jar
      depends_on:
          - postgres
      networks:
        default:

  adminer:
      image: adminer

      depends_on:
          - postgres
      network_mode: "host"

networks:
    default:










